<?php

declare(strict_types=1);

use App\Application\Synthesis\SynthesisService;
use App\Domain\Synthesis\ArticleContentFetcherInterface;
use App\Domain\Synthesis\FetchedContent;
use App\Domain\Synthesis\InvalidSynthesisUrlException;
use App\Domain\Synthesis\MistralClientInterface;
use App\Domain\Synthesis\SynthesisRequest;
use App\Domain\Synthesis\SynthesisResult;
use App\Domain\Synthesis\SynthesisResultRepositoryInterface;
use App\Domain\Synthesis\SynthesisUnavailableException;
use Psr\Log\NullLogger;

/*
 * Unit tests — SynthesisService (Application layer)
 *
 * Couvre les scénarios Gherkin US-010 (T-010-10) :
 *   - Nominal : URL valide → SynthesisResponse avec préfixe "BRIEFLY AI:"
 *   - SSRF bloqué : IP privée → InvalidSynthesisUrlException sans appel Mistral
 *   - SSRF bloqué : localhost → InvalidSynthesisUrlException sans appel Mistral
 *   - SSRF bloqué : URL malformée → InvalidSynthesisUrlException sans appel Mistral
 *   - Contenu partiel (paywall) → SynthesisResponse avec isPartial=true
 *   - Timeout Mistral → SynthesisUnavailableException
 *   - PII-free : le prompt Mistral ne contient aucun UUID utilisateur ni email
 *   - url_hash SHA-256 stocké dans SynthesisResult
 *
 * Tous les ports sont mockés (stubs PHP anonymes — pas de Mockery/PHPUnit mock builder).
 */

// ── Stubs ──────────────────────────────────────────────────────────────────────

/**
 * Stub MistralClientInterface — retourne une réponse prédéfinie ou lève une exception.
 */
function mistralClientStub(
    string $response = '',
    bool $throwUnavailable = false,
): MistralClientInterface {
    return new class($response, $throwUnavailable) implements MistralClientInterface {
        /** @var string[] */
        public array $capturedPrompts = [];

        public function __construct(
            private readonly string $response,
            private readonly bool $throw,
        ) {
        }

        public function complete(string $systemPrompt, string $userContent): string
        {
            $this->capturedPrompts[] = $systemPrompt . "\n\n" . $userContent;

            if ($this->throw) {
                throw new SynthesisUnavailableException('mock Mistral timeout');
            }

            return $this->response ?: <<<'MISTRAL'
                BRIEFLY AI: This is a test summary of the article content provided. It covers the main points and provides
                a concise overview of approximately two hundred words. The article discusses important topics relevant to
                the tech industry and provides insight into current trends. This summary is generated by artificial intelligence
                and represents a condensed version of the original content for quick consumption.

                KEY POINTS:
                01 First key point from the article content
                02 Second key point from the article content
                03 Third key point from the article content

                SOURCES:
                Test Source
                MISTRAL;
        }
    };
}

/**
 * Stub ArticleContentFetcherInterface — retourne du contenu paramétrable.
 */
function contentFetcherStub(
    string $text = 'Article content for testing purposes. This is a long enough text to pass the paywall detection threshold.',
    bool $isPartial = false,
): ArticleContentFetcherInterface {
    return new class($text, $isPartial) implements ArticleContentFetcherInterface {
        public function __construct(
            private readonly string $text,
            private readonly bool $isPartial,
        ) {
        }

        public function fetchContent(string $url): FetchedContent
        {
            return new FetchedContent(text: $this->text, isPartial: $this->isPartial);
        }
    };
}

/**
 * Stub SynthesisResultRepositoryInterface — capture les SynthesisResult sauvegardés.
 */
function repositoryStub(): SynthesisResultRepositoryInterface
{
    return new class implements SynthesisResultRepositoryInterface {
        /** @var SynthesisResult[] */
        public array $saved = [];

        public function save(SynthesisResult $result): void
        {
            $this->saved[] = $result;
        }
    };
}

/**
 * Construit un SynthesisService avec les stubs fournis.
 */
function makeSynthesisService(
    MistralClientInterface $mistral,
    ArticleContentFetcherInterface $fetcher,
    SynthesisResultRepositoryInterface $repository,
): SynthesisService {
    return new SynthesisService(
        mistralClient: $mistral,
        contentFetcher: $fetcher,
        repository: $repository,
        logger: new NullLogger(),
    );
}

// ── Scénario nominal ──────────────────────────────────────────────────────────

test('synthesize retourne une SynthesisResponse avec préfixe "BRIEFLY AI:" pour URL valide', function (): void {
    $service = makeSynthesisService(
        mistral: mistralClientStub(),
        fetcher: contentFetcherStub(),
        repository: repositoryStub(),
    );

    $response = $service->synthesize(new SynthesisRequest('https://example.com/article'));

    expect($response->content)->toStartWith('BRIEFLY AI:');
    expect($response->originalUrl)->toBe('https://example.com/article');
    expect($response->isPartial)->toBeFalse();
});

test('synthesize retourne exactement 3 points clés numérotés 01/02/03', function (): void {
    $service = makeSynthesisService(
        mistral: mistralClientStub(),
        fetcher: contentFetcherStub(),
        repository: repositoryStub(),
    );

    $response = $service->synthesize(new SynthesisRequest('https://example.com/article'));

    expect($response->keyPoints)->toHaveCount(3);
    expect($response->keyPoints[0])->toStartWith('01');
    expect($response->keyPoints[1])->toStartWith('02');
    expect($response->keyPoints[2])->toStartWith('03');
});

test('synthesize retourne au moins une source', function (): void {
    $service = makeSynthesisService(
        mistral: mistralClientStub(),
        fetcher: contentFetcherStub(),
        repository: repositoryStub(),
    );

    $response = $service->synthesize(new SynthesisRequest('https://example.com/article'));

    expect($response->sources)->not->toBeEmpty();
});

test('synthesize persiste le résultat avec url_hash SHA-256', function (): void {
    $repo = repositoryStub();
    $service = makeSynthesisService(
        mistral: mistralClientStub(),
        fetcher: contentFetcherStub(),
        repository: $repo,
    );

    $url = 'https://example.com/article';
    $service->synthesize(new SynthesisRequest($url));

    expect($repo->saved)->toHaveCount(1);

    $saved = $repo->saved[0];
    expect($saved->getUrlHash())->toBe(hash('sha256', $url));
    expect($saved->getLevel())->toBe('standard');
});

// ── Scénario alternatif 1 — Paywall (contenu partiel) ────────────────────────

test('synthesize retourne isPartial=true quand le fetcher signale un paywall', function (): void {
    $service = makeSynthesisService(
        mistral: mistralClientStub(),
        fetcher: contentFetcherStub(isPartial: true),
        repository: repositoryStub(),
    );

    $response = $service->synthesize(new SynthesisRequest('https://example.com/paywalled'));

    expect($response->isPartial)->toBeTrue();
    expect($response->content)->toContain('Contenu partiel');
});

test('synthesize retourne toujours "BRIEFLY AI:" même avec contenu partiel', function (): void {
    $service = makeSynthesisService(
        mistral: mistralClientStub(),
        fetcher: contentFetcherStub(isPartial: true),
        repository: repositoryStub(),
    );

    $response = $service->synthesize(new SynthesisRequest('https://example.com/paywalled'));

    expect($response->content)->toStartWith('BRIEFLY AI:');
});

// ── Scénario erreur 1 — URL invalide / SSRF ───────────────────────────────────

test('synthesize lève InvalidSynthesisUrlException pour URL malformée', function (): void {
    $service = makeSynthesisService(
        mistral: mistralClientStub(),
        fetcher: contentFetcherStub(),
        repository: repositoryStub(),
    );

    expect(static fn () => $service->synthesize(new SynthesisRequest('httpp://invalid..com')))
        ->toThrow(InvalidSynthesisUrlException::class);
});

test('synthesize lève InvalidSynthesisUrlException pour IP privée RFC1918 10.x.x.x (SSRF)', function (): void {
    $service = makeSynthesisService(
        mistral: mistralClientStub(),
        fetcher: contentFetcherStub(),
        repository: repositoryStub(),
    );

    expect(static fn () => $service->synthesize(new SynthesisRequest('http://10.0.0.1/internal')))
        ->toThrow(InvalidSynthesisUrlException::class);
});

test('synthesize lève InvalidSynthesisUrlException pour IP privée RFC1918 192.168.x.x (SSRF)', function (): void {
    $service = makeSynthesisService(
        mistral: mistralClientStub(),
        fetcher: contentFetcherStub(),
        repository: repositoryStub(),
    );

    expect(static fn () => $service->synthesize(new SynthesisRequest('http://192.168.1.1/admin')))
        ->toThrow(InvalidSynthesisUrlException::class);
});

test('synthesize lève InvalidSynthesisUrlException pour IP privée RFC1918 172.16.x.x (SSRF)', function (): void {
    $service = makeSynthesisService(
        mistral: mistralClientStub(),
        fetcher: contentFetcherStub(),
        repository: repositoryStub(),
    );

    expect(static fn () => $service->synthesize(new SynthesisRequest('http://172.16.0.1/internal')))
        ->toThrow(InvalidSynthesisUrlException::class);
});

test('synthesize lève InvalidSynthesisUrlException pour localhost (SSRF)', function (): void {
    $service = makeSynthesisService(
        mistral: mistralClientStub(),
        fetcher: contentFetcherStub(),
        repository: repositoryStub(),
    );

    expect(static fn () => $service->synthesize(new SynthesisRequest('http://localhost/secret')))
        ->toThrow(InvalidSynthesisUrlException::class);
});

test('synthesize lève InvalidSynthesisUrlException pour 127.0.0.1 (SSRF loopback)', function (): void {
    $service = makeSynthesisService(
        mistral: mistralClientStub(),
        fetcher: contentFetcherStub(),
        repository: repositoryStub(),
    );

    expect(static fn () => $service->synthesize(new SynthesisRequest('http://127.0.0.1/secret')))
        ->toThrow(InvalidSynthesisUrlException::class);
});

test('synthesize NE contacte PAS Mistral si URL invalide (SSRF bloqué)', function (): void {
    $mistral = mistralClientStub();
    $service = makeSynthesisService(
        mistral: $mistral,
        fetcher: contentFetcherStub(),
        repository: repositoryStub(),
    );

    try {
        $service->synthesize(new SynthesisRequest('http://192.168.1.1/admin'));
    } catch (InvalidSynthesisUrlException) {
        // attendu
    }

    expect($mistral->capturedPrompts)->toBeEmpty();
});

test('synthesize lève InvalidSynthesisUrlException pour schéma file:// (non http/https)', function (): void {
    $service = makeSynthesisService(
        mistral: mistralClientStub(),
        fetcher: contentFetcherStub(),
        repository: repositoryStub(),
    );

    expect(static fn () => $service->synthesize(new SynthesisRequest('file:///etc/passwd')))
        ->toThrow(InvalidSynthesisUrlException::class);
});

// ── Scénario erreur 2 — Timeout Mistral ──────────────────────────────────────

test('synthesize lève SynthesisUnavailableException si Mistral timeout', function (): void {
    $service = makeSynthesisService(
        mistral: mistralClientStub(throwUnavailable: true),
        fetcher: contentFetcherStub(),
        repository: repositoryStub(),
    );

    expect(static fn () => $service->synthesize(new SynthesisRequest('https://example.com/article')))
        ->toThrow(SynthesisUnavailableException::class);
});

test('synthesize NE persiste PAS si Mistral timeout (SynthesisResult non sauvegardé)', function (): void {
    $repo = repositoryStub();
    $service = makeSynthesisService(
        mistral: mistralClientStub(throwUnavailable: true),
        fetcher: contentFetcherStub(),
        repository: $repo,
    );

    try {
        $service->synthesize(new SynthesisRequest('https://example.com/article'));
    } catch (SynthesisUnavailableException) {
        // attendu
    }

    expect($repo->saved)->toBeEmpty();
});

// ── PII-free assertion (T-010-11) ─────────────────────────────────────────────

test('le prompt envoyé à Mistral ne contient aucun UUID utilisateur (PII-free)', function (): void {
    $mistral = mistralClientStub();
    $service = makeSynthesisService(
        mistral: $mistral,
        fetcher: contentFetcherStub(),
        repository: repositoryStub(),
    );

    $service->synthesize(new SynthesisRequest('https://example.com/article'));

    $capturedPrompt = implode(' ', $mistral->capturedPrompts);

    // Pattern UUID v4 (RFC 4122)
    expect($capturedPrompt)->not->toMatch(
        '/[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/i',
    );
});

test('le prompt envoyé à Mistral ne contient aucun email (PII-free)', function (): void {
    $mistral = mistralClientStub();
    $service = makeSynthesisService(
        mistral: $mistral,
        fetcher: contentFetcherStub(),
        repository: repositoryStub(),
    );

    $service->synthesize(new SynthesisRequest('https://example.com/article'));

    $capturedPrompt = implode(' ', $mistral->capturedPrompts);

    // Pattern email basique
    expect($capturedPrompt)->not->toMatch('/[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}/');
});
